image:
  repository: registry.local:5000/githedgehog/das-boot-seeder
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  clusterIP: 10.143.42.42
  ports:
    # insecure:
    #   port: 80
    #   targetPort: 8080
    secure:
      port: 443
      targetPort: 8443
settings:
  issue_certificates: false
  listeners:
    insecure:
      dynll:
        device_name: ""
        listening_port: 80
  control_vip: "192.168.42.1"
  ntp_servers:
    - hh-ntp-udp.default.svc.cluster.local
  syslog_servers:
    - hh-syslog-rsyslog.default.svc.cluster.local
  kube_subnets:
    - 10.142.0.0/16
    - 10.143.0.0/16
  artifacts:
    oci_temp_dir: /tmp/oci-file-stores
    oci_registries:
    - url: oci://registry.local:5000/githedgehog
      ca:
        secretName: oci-ca
        certKey: cert.pem
        mountPath: /etc/hedgehog/seeder-certs/oci-ca
securityContext:
  privileged: true
  runAsUser: 0
  runAsGroup: 0