image:
  repository: registry.local:5000/githedgehog/das-boot
  tag: latest
  pullPolicy: Always
settings:
  issue_certificates: true
  listeners:
    insecure:
    - ":80"
  ntp_servers:
    - hedgehog-ntp-udp.default.svc.cluster.local
  syslog_servers:
    - hedgehog-syslog-rsyslog.default.svc.cluster.local
  artifacts:
    oci_registries:
    - url: oci://registry.local:5000/githedgehog
      ca:
        secretName: oci-ca
        certKey: cert.pem
        mountPath: /etc/hedgehog/seeder-certs/oci-ca
securityContext:
  privileged: true
  runAsUser: 0
  runAsGroup: 0