image:
  repository: registry.local:5000/githedgehog/das-boot
  tag: latest
  pullPolicy: Always
settings:
  issue_certificates: true
  ntp_servers:
    - hedgehog-ntp-udp.default.svc.cluster.local
  syslog_servers:
    - hedgehog-syslog-syslog-ng.default.svc.cluster.local