# Copyright 2023 Hedgehog
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

###
### rack-1
###
---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Rack
metadata:
  labels:
  name: rack-1
spec:
###
### switch-1
###
---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Switch
metadata:
  labels:
    fabric.githedgehog.com/rack: rack-1
    fabric.githedgehog.com/location: b7e0848d-15f9-5f46-ac21-1710a7b792f0
  name: switch-1
spec:
  lldp: {}
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "1"
  locationSig:
    sig: "long-signature"
    uuidSig: "also-long-signature"
###
### switch-2
###
---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Switch
metadata:
  labels:
    fabric.githedgehog.com/rack: rack-1
    fabric.githedgehog.com/location: 81c9671f-0b80-5a45-b946-686de0b9aaa9
  name: switch-2
spec:
  lldp: {}
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "2"
  locationSig:
    sig: "long-signature"
    uuidSig: "also-long-signature"
###
### control-node-1
###
---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/rack: rack-1
  name: control-node-1
spec:
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "3"
  locationSig:
    sig: "long-signature"
    uuidSig: "also-long-signature"
  type: control
###
### compute-1
###
---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/rack: rack-1
  name: compute-1
spec:
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "4"
  locationSig:
    sig: "long-signature"
    uuidSig: "also-long-signature"
###
### compute-2
###
---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/rack: rack-1
  name: compute-2
spec:
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "5"
  locationSig:
    sig: "long-signature"
    uuidSig: "also-long-signature"
###
### compute-3
###
---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/rack: rack-1
  name: compute-3
spec:
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "6"
  locationSig:
    sig: "long-signature"
    uuidSig: "also-long-signature"
---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/rack: rack-1
  name: compute-4
spec:
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "7"
  locationSig:
    sig: "long-signature"
    uuidSig: "also-long-signature"
---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    server.fabric.githedgehog.com/compute-1: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
    rack.fabric.githedgehog.com/rack-1: "true"
  name: compute-1--mclag--switch-1--switch-2
spec:
  mclag:
    links:
    - server:
        port: compute-1/nic0/port0
      switch:
        port: switch-1/Ethernet2
    - server:
        port: compute-1/nic0/port1
      switch:
        port: switch-2/Ethernet2
---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    server.fabric.githedgehog.com/compute-2: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
    rack.fabric.githedgehog.com/rack-1: "true"
  name: compute-2--mclag--switch-1--switch-2
spec:
  mclag:
    links:
    - server:
        port: compute-2/nic0/port0
      switch:
        port: switch-1/Ethernet3
    - server:
        port: compute-2/nic0/port1
      switch:
        port: switch-2/Ethernet3
---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    server.fabric.githedgehog.com/compute-3: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
    rack.fabric.githedgehog.com/rack-1: "true"
  name: compute-3--unbundled--switch-1
spec:
  unbundled:
    link:
      server:
        port: compute-3/nic0/port0
      switch:
        port: switch-1/Ethernet4
---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    server.fabric.githedgehog.com/compute-4: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
    rack.fabric.githedgehog.com/rack-1: "true"
  name: compute-4--unbundled--switch-2
spec:
  unbundled:
    link:
      server:
        port: compute-4/nic0/port0
      switch:
        port: switch-2/Ethernet4
---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    server.fabric.githedgehog.com/control-node-1: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
    rack.fabric.githedgehog.com/rack-1: "true"
  name: control-node-1--mgmt--switch-1
spec:
  management:
    link:
      server:
        port: control-node-1/switch1
        ip: 192.168.101.1/31
      switch:
        ip: 192.168.101.0/31
        oniePortName: eth1
        port: switch-1/Management0
---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    server.fabric.githedgehog.com/control-node-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
  name: control-node-1--mgmt--switch-2
spec:
  management:
    link:
      server:
        port: control-node-1/switch2
        ip: 192.168.102.1/31
      switch:
        ip: 192.168.102.0/31
        oniePortName: eth1
        port: switch-2/Management0
---
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    server.fabric.githedgehog.com/switch-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
    rack.fabric.githedgehog.com/rack-1: "true"
  name: switch-1--mclag-domain--switch-2
spec:
  mclagDomain:
    links:
    - switch1:
        port: switch-1/Ethernet0
      switch2:
        port: switch-2/Ethernet0
    - switch1:
        port: switch-1/Ethernet1
      switch2:
        port: switch-2/Ethernet1
