---
name: Continuous Integration (PRs)
on:
  pull_request:
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true
jobs:
  build:
    runs-on: lab
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      - name: install dependencies
        run: make install-deps
      - name: Run code generators
        run: make generate
      - name: run builds
        run: make build
      # NOTE: disable uploading of build artifacts in PRs
      # - name: Archive build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-artifacts
      #     path: |
      #       build/artifacts
      #       !build/artifacts/.keepme
  test:
    runs-on: lab
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      - name: install dependencies
        run: make install-deps
      - name: Run code generators
        run: make generate
      - name: run builds
        run: make build
      - name: initialize testdata
        run: ./scripts/init_testdata.sh
        shell: bash
      - name: unit tests with code coverage
        run: |
          make test-cover
          echo "### Code Coverage" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo -n "Total Code Coverage: " >> $GITHUB_STEP_SUMMARY
          tail -n 1 ./build/coverage/coverage.out | awk '{ print "**"$3"**" }' >> $GITHUB_STEP_SUMMARY
          echo -n "" >> $GITHUB_STEP_SUMMARY
          echo -n "Look at coverage report in the artifacts for details." >> $GITHUB_STEP_SUMMARY
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: build/coverage/coverage.html
      - name: unit tests with race detector
        run: make test-race
  lint:
    runs-on: lab
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      - name: install dependencies
        run: make install-deps
      - name: Run code generators
        run: make generate
      - name: run builds
        run: make build
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --verbose ./...
