---
name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: '~1.20.1'
          cache: true
      - name: install dependencies
        run: make install-deps
      - name: Run code generators
        run: make generate
      - name: run builds
        run: make build
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            build/artifacts
            !build/artifacts/.keepme
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: '~1.20.1'
          cache: true
      - name: install dependencies
        run: make install-deps
      - name: Run code generators
        run: make generate
      - name: initialize testdata
        run: ./scripts/init_testdata.sh
        shell: bash
      - name: run tests with code coverage
        run: |
          make test-cover
          echo "### Code Coverage" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo -n "Total Code Coverage: " >> $GITHUB_STEP_SUMMARY
          tail -n 1 ./build/coverage/coverage.out | awk '{ print $3 }' >> $GITHUB_STEP_SUMMARY
          echo -n "" >> $GITHUB_STEP_SUMMARY
          echo -n "Look at coverage report in the artifacts for details." >> $GITHUB_STEP_SUMMARY
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: build/coverage/coverage.html
      - name: run tests with race detector
        run: make test-race
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: '~1.20.1'
          cache: true
      - name: install dependencies
        run: make install-deps
      - name: Run code generators
        run: make generate
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --verbose ./...
          # unfortunately the package cache is creating lots of errors/warnings right now
          # for details: https://github.com/golangci/golangci-lint-action/issues/677
          skip-pkg-cache: true
