---
name: Continuous Integration (main branch + manual trigger)
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  build:
    env:
      GOPRIVATE: go.githedgehog.com
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '~1.21.1'
          cache: true
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: install dependencies
        run: make install-deps
      - name: Run code generators
        run: make generate
      - name: run builds
        run: make build
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            build/artifacts
            !build/artifacts/.keepme
  test:
    env:
      GOPRIVATE: go.githedgehog.com
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '~1.21.1'
          cache: true
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: install dependencies
        run: make install-deps
      - name: Run code generators
        run: make generate
      - name: run builds
        run: make build
      - name: initialize testdata
        run: ./scripts/init_testdata.sh
        shell: bash
      - name: unit tests with code coverage
        run: |
          make test-cover
          echo "### Code Coverage" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo -n "Total Code Coverage: " >> $GITHUB_STEP_SUMMARY
          tail -n 1 ./build/coverage/coverage.out | awk '{ print "**"$3"**" }' >> $GITHUB_STEP_SUMMARY
          echo -n "" >> $GITHUB_STEP_SUMMARY
          echo -n "Look at coverage report in the artifacts for details." >> $GITHUB_STEP_SUMMARY
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: build/coverage/coverage.html
      - name: unit tests with race detector
        run: make test-race
  lint:
    env:
      GOPRIVATE: go.githedgehog.com
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '~1.21.1'
          cache: true
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: install dependencies
        run: make install-deps
      - name: Run code generators
        run: make generate
      - name: run builds
        run: make build
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --verbose ./...
          # unfortunately the package cache is creating lots of errors/warnings right now
          # for details: https://github.com/golangci/golangci-lint-action/issues/677
          skip-pkg-cache: true

  publish:
    name: Publish to GitHub Packages
    if: startsWith(github.event.ref, 'refs/tags/') && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs:
      - build
      - test
      - lint
    env:
      GOPRIVATE: go.githedgehog.com
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
          cache: true

      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/

      - name: install dependencies
        run: make install-deps

      - name: Run code generators
        run: make generate

      - name: run builds
        run: make build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        # temp
        run:
          make docker-push DOCKER_REPO=ghcr.io/githedgehog/das-boot DOCKER_VERSION=$(git describe --tags --dirty --always)
          make helm-push HELM_CHART_REPO=ghcr.io/githedgehog/das-boot/charts HELM_CHART_VERSION=$(git describe --tags --dirty --always)
